# Generated by Django 5.2.12 on 2026-04-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_remove_comic_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='age_rating',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='16+', max_length=4),
        ),
        migrations.AddField(
            model_name='comicuploaddraft',
            name='age_rating',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='16+', max_length=4),
        ),
    ]
