# Generated by Django 5.2.12 on 2026-04-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_comic_age_rating_comicuploaddraft_age_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComicComment',
        ),
    ]
